This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file /Users/hmoreau/Documents/Personnel/Emploi/UPC/cpe-failure-prediction/report/Thesis_Hugo_MOREAU/.texpadtmp/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/hmoreau/Documents/Personnel/Emploi/UPC/cpe-failure-prediction/report/Thesis_Hugo_MOREAU/.texpadtmp/main.acn....done (279 entries accepted, 0 rejected).
Sorting entries.....done (2441 comparisons).
Generating output file /Users/hmoreau/Documents/Personnel/Emploi/UPC/cpe-failure-prediction/report/Thesis_Hugo_MOREAU/.texpadtmp/main.acr....done (101 lines written, 0 warnings).
Output written in /Users/hmoreau/Documents/Personnel/Emploi/UPC/cpe-failure-prediction/report/Thesis_Hugo_MOREAU/.texpadtmp/main.acr.
Transcript written in /Users/hmoreau/Documents/Personnel/Emploi/UPC/cpe-failure-prediction/report/Thesis_Hugo_MOREAU/.texpadtmp/main.alg.
