/*
AUTHOR:
    Hugo Moreau - hugo.moreau@epfl.ch
    Msc in Communication Systems
    Minor in Management and Technological Entrepreneurship

DESCRIPTION:
    As a package containing references to non-existant tables cannot compile we
    need an external package to help us create such tables. This package will help to 
    relaunch the POC once tables have been deleted. 

EXECUTION:
    BEGIN
        HUMOREAU.CPE_FAIL_DETECTION_POC_INIT.INITIALIZE;
    END;
*/

CREATE OR REPLACE PACKAGE CPE_FAIL_DETECTION_POC_INIT 
IS
    print_perf                      BOOLEAN     := TRUE;
    already_existing_tables         NUMBER;

    PROCEDURE INITIALIZE;
    PROCEDURE INIT_VECTOR;
    PROCEDURE INIT_VIA;
    PROCEDURE INIT_LOGTABLE;
    PROCEDURE INIT_SAMPLING;

    -- Utils
    PROCEDURE CHECK_STATE;

    -- Exception
    INVALID_STATE                   EXCEPTION;


END CPE_FAIL_DETECTION_POC_INIT;
/
CREATE OR REPLACE PACKAGE BODY CPE_FAIL_DETECTION_POC_INIT IS 

    /*
    Checks that indeed none of the tables exist already. 

    @raises:
    - INVALID_STATE: if one of the table that should be created by the INIT procedure already exists.
    */
    PROCEDURE CHECK_STATE IS
    BEGIN
        select count(*) into already_existing_tables from all_tables where owner = 'HUMOREAU' and table_name in ('VECTOR_FIVE_DAYS_II','VIA_MACS','SAMPLED_VECTORS','LOG_TABLE');
        if(already_existing_tables>0) then 
            RAISE INVALID_STATE;
        end if;
    END;

    /*
    In order to restart the package. It will create the 3 necessary tables: VECTRO_FIVE_DAYS_II, VIA_MACS and SAMPLED_VECTORS
    */    
    PROCEDURE INITIALIZE IS 
    BEGIN
        CHECK_STATE;
        INIT_VECTOR;
        INIT_VIA;
        INIT_SAMPLING;
        INIT_LOGTABLE;
    END INITIALIZE;

    /*
    Creates VECTRO_FIVE_DAYS_II
    */
    PROCEDURE INIT_VECTOR AS
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE humoreau.VECTRO_FIVE_DAYS_II (
            DAY_0 DATE ,
            MAC VARCHAR2(320) ,
            CLY_ACCOUNT_NUMBER VARCHAR2(100 CHAR) ,
            SAA_ACCOUNT_NUMBER VARCHAR2(256 CHAR) ,
            CMTS VARCHAR2(50 CHAR) ,
            SERVICE_GROUP VARCHAR2(50 CHAR) ,
            HARDWARE_MODEL VARCHAR2(80 CHAR) ,
            N_CPE_BUILDING NUMBER ,
            OFFLINE_PCT_6H NUMBER ,
            OFFLINE_PCT_12H NUMBER ,
            OFFLINE_PCT_18H NUMBER ,
            OFFLINE_PCT_24H NUMBER ,
            OFFLINE_PCT NUMBER ,
            OFFLINE_PCT_1D NUMBER ,
            OFFLINE_PCT_2D NUMBER ,
            OFFLINE_PCT_3D NUMBER ,
            OFFLINE_PCT_4D NUMBER ,
            OFFLINE_PCT_5D NUMBER ,
            CER_DN_6H NUMBER ,
            CER_DN_12H NUMBER ,
            CER_DN_18H NUMBER ,
            CER_DN NUMBER ,
            CER_DN_1D NUMBER ,
            CER_DN_2D NUMBER ,
            CER_DN_3D NUMBER ,
            CER_DN_4D NUMBER ,
            CER_DN_5D NUMBER ,
            MISS_CER_DN_6H NUMBER ,
            MISS_CER_DN_12H NUMBER ,
            MISS_CER_DN_18H NUMBER ,
            MISS_CER_DN_24H NUMBER ,
            MISS_CER_DN NUMBER ,
            MISS_CER_DN_1D NUMBER ,
            MISS_CER_DN_2D NUMBER ,
            MISS_CER_DN_3D NUMBER ,
            MISS_CER_DN_4D NUMBER ,
            MISS_CER_DN_5D NUMBER ,
            CER_UP_6H NUMBER ,
            CER_UP_12H NUMBER ,
            CER_UP_18H NUMBER ,
            CER_UP NUMBER ,
            CER_UP_1D NUMBER ,
            CER_UP_2D NUMBER ,
            CER_UP_3D NUMBER ,
            CER_UP_4D NUMBER ,
            CER_UP_5D NUMBER ,
            MISS_CER_UP_6H NUMBER ,
            MISS_CER_UP_12H NUMBER ,
            MISS_CER_UP_18H NUMBER ,
            MISS_CER_UP_24H NUMBER ,
            MISS_CER_UP NUMBER ,
            MISS_CER_UP_1D NUMBER ,
            MISS_CER_UP_2D NUMBER ,
            MISS_CER_UP_3D NUMBER ,
            MISS_CER_UP_4D NUMBER ,
            MISS_CER_UP_5D NUMBER ,
            PCT_TRAFFIC_DMH_UP_6H NUMBER ,
            PCT_TRAFFIC_DMH_UP_12H NUMBER ,
            PCT_TRAFFIC_DMH_UP_18H NUMBER ,
            PCT_TRAFFIC_DMH_UP NUMBER ,
            PCT_TRAFFIC_DMH_UP_1D NUMBER ,
            PCT_TRAFFIC_DMH_UP_2D NUMBER ,
            PCT_TRAFFIC_DMH_UP_3D NUMBER ,
            PCT_TRAFFIC_DMH_UP_4D NUMBER ,
            PCT_TRAFFIC_DMH_UP_5D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_6H NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_12H NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_18H NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_24H NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_1D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_2D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_3D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_4D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_5D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_6H NUMBER ,
            PCT_TRAFFIC_SDMH_UP_12H NUMBER ,
            PCT_TRAFFIC_SDMH_UP_18H NUMBER ,
            PCT_TRAFFIC_SDMH_UP NUMBER ,
            PCT_TRAFFIC_SDMH_UP_1D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_2D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_3D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_4D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_5D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_6H NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_12H NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_18H NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_24H NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_1D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_2D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_3D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_4D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_5D NUMBER ,
            RX_DN_6H NUMBER ,
            RX_DN_12H NUMBER ,
            RX_DN_18H NUMBER ,
            RX_DN NUMBER ,
            RX_DN_1D NUMBER ,
            RX_DN_2D NUMBER ,
            RX_DN_3D NUMBER ,
            RX_DN_4D NUMBER ,
            RX_DN_5D NUMBER ,
            MISS_RX_DN_6H NUMBER ,
            MISS_RX_DN_12H NUMBER ,
            MISS_RX_DN_18H NUMBER ,
            MISS_RX_DN_24H NUMBER ,
            MISS_RX_DN NUMBER ,
            MISS_RX_DN_1D NUMBER ,
            MISS_RX_DN_2D NUMBER ,
            MISS_RX_DN_3D NUMBER ,
            MISS_RX_DN_4D NUMBER ,
            MISS_RX_DN_5D NUMBER ,
            RX_UP_6H NUMBER ,
            RX_UP_12H NUMBER ,
            RX_UP_18H NUMBER ,
            RX_UP NUMBER ,
            RX_UP_1D NUMBER ,
            RX_UP_2D NUMBER ,
            RX_UP_3D NUMBER ,
            RX_UP_4D NUMBER ,
            RX_UP_5D NUMBER ,
            MISS_RX_UP_6H NUMBER ,
            MISS_RX_UP_12H NUMBER ,
            MISS_RX_UP_18H NUMBER ,
            MISS_RX_UP_24H NUMBER ,
            MISS_RX_UP NUMBER ,
            MISS_RX_UP_1D NUMBER ,
            MISS_RX_UP_2D NUMBER ,
            MISS_RX_UP_3D NUMBER ,
            MISS_RX_UP_4D NUMBER ,
            MISS_RX_UP_5D NUMBER ,
            SNR_DN_6H NUMBER ,
            SNR_DN_12H NUMBER ,
            SNR_DN_18H NUMBER ,
            SNR_DN NUMBER ,
            SNR_DN_1D NUMBER ,
            SNR_DN_2D NUMBER ,
            SNR_DN_3D NUMBER ,
            SNR_DN_4D NUMBER ,
            SNR_DN_5D NUMBER ,
            MISS_SNR_DN_6H NUMBER ,
            MISS_SNR_DN_12H NUMBER ,
            MISS_SNR_DN_18H NUMBER ,
            MISS_SNR_DN_24H NUMBER ,
            MISS_SNR_DN NUMBER ,
            MISS_SNR_DN_1D NUMBER ,
            MISS_SNR_DN_2D NUMBER ,
            MISS_SNR_DN_3D NUMBER ,
            MISS_SNR_DN_4D NUMBER ,
            MISS_SNR_DN_5D NUMBER ,
            SNR_UP_6H NUMBER ,
            SNR_UP_12H NUMBER ,
            SNR_UP_18H NUMBER ,
            SNR_UP NUMBER ,
            SNR_UP_1D NUMBER ,
            SNR_UP_2D NUMBER ,
            SNR_UP_3D NUMBER ,
            SNR_UP_4D NUMBER ,
            SNR_UP_5D NUMBER ,
            MISS_SNR_UP_6H NUMBER ,
            MISS_SNR_UP_12H NUMBER ,
            MISS_SNR_UP_18H NUMBER ,
            MISS_SNR_UP_24H NUMBER ,
            MISS_SNR_UP NUMBER ,
            MISS_SNR_UP_1D NUMBER ,
            MISS_SNR_UP_2D NUMBER ,
            MISS_SNR_UP_3D NUMBER ,
            MISS_SNR_UP_4D NUMBER ,
            MISS_SNR_UP_5D NUMBER ,
            TX_UP_6H NUMBER ,
            TX_UP_12H NUMBER ,
            TX_UP_18H NUMBER ,
            TX_UP NUMBER ,
            TX_UP_1D NUMBER ,
            TX_UP_2D NUMBER ,
            TX_UP_3D NUMBER ,
            TX_UP_4D NUMBER ,
            TX_UP_5D NUMBER ,
            MISS_TX_UP_6H NUMBER ,
            MISS_TX_UP_12H NUMBER ,
            MISS_TX_UP_18H NUMBER ,
            MISS_TX_UP_24H NUMBER ,
            MISS_TX_UP NUMBER ,
            MISS_TX_UP_1D NUMBER ,
            MISS_TX_UP_2D NUMBER ,
            MISS_TX_UP_3D NUMBER ,
            MISS_TX_UP_4D NUMBER ,
            MISS_TX_UP_5D NUMBER ,
            CMTS_RX_UP_6H NUMBER ,
            CMTS_RX_UP_12H NUMBER ,
            CMTS_RX_UP_18H NUMBER ,
            CMTS_RX_UP NUMBER ,
            CMTS_RX_UP_1D NUMBER ,
            CMTS_RX_UP_2D NUMBER ,
            CMTS_RX_UP_3D NUMBER ,
            CMTS_RX_UP_4D NUMBER ,
            CMTS_RX_UP_5D NUMBER ,
            CMTS_TX_UP_6H NUMBER ,
            CMTS_TX_UP_12H NUMBER ,
            CMTS_TX_UP_18H NUMBER ,
            CMTS_TX_UP NUMBER ,
            CMTS_TX_UP_1D NUMBER ,
            CMTS_TX_UP_2D NUMBER ,
            CMTS_TX_UP_3D NUMBER ,
            CMTS_TX_UP_4D NUMBER ,
            CMTS_TX_UP_5D NUMBER ,
            CMTS_CER_UP_6H NUMBER ,
            CMTS_CER_UP_12H NUMBER ,
            CMTS_CER_UP_18H NUMBER ,
            CMTS_CER_UP NUMBER ,
            CMTS_CER_UP_1D NUMBER ,
            CMTS_CER_UP_2D NUMBER ,
            CMTS_CER_UP_3D NUMBER ,
            CMTS_CER_UP_4D NUMBER ,
            CMTS_CER_UP_5D NUMBER ,
            CMTS_UTILIZATION_UP_6H NUMBER ,
            CMTS_UTILIZATION_UP_12H NUMBER ,
            CMTS_UTILIZATION_UP_18H NUMBER ,
            CMTS_UTILIZATION_UP NUMBER ,
            CMTS_UTILIZATION_UP_1D NUMBER ,
            CMTS_UTILIZATION_UP_2D NUMBER ,
            CMTS_UTILIZATION_UP_3D NUMBER ,
            CMTS_UTILIZATION_UP_4D NUMBER ,
            CMTS_UTILIZATION_UP_5D NUMBER ,
            CMTS_MS_UTILIZATION_UP_6H NUMBER ,
            CMTS_MS_UTILIZATION_UP_12H NUMBER ,
            CMTS_MS_UTILIZATION_UP_18H NUMBER ,
            CMTS_MS_UTILIZATION_UP NUMBER ,
            CMTS_MS_UTILIZATION_UP_1D NUMBER ,
            CMTS_MS_UTILIZATION_UP_2D NUMBER ,
            CMTS_MS_UTILIZATION_UP_3D NUMBER ,
            CMTS_MS_UTILIZATION_UP_4D NUMBER ,
            CMTS_MS_UTILIZATION_UP_5D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_6H NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_12H NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_18H NUMBER ,
            CMTS_F_MS_UTILIZATION_UP NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_1D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_2D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_3D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_4D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_5D NUMBER ,
            CMTS_RX_DN_6H NUMBER ,
            CMTS_RX_DN_12H NUMBER ,
            CMTS_RX_DN_18H NUMBER ,
            CMTS_RX_DN NUMBER ,
            CMTS_RX_DN_1D NUMBER ,
            CMTS_RX_DN_2D NUMBER ,
            CMTS_RX_DN_3D NUMBER ,
            CMTS_RX_DN_4D NUMBER ,
            CMTS_RX_DN_5D NUMBER ,
            CMTS_SNR_DN_6H NUMBER ,
            CMTS_SNR_DN_12H NUMBER ,
            CMTS_SNR_DN_18H NUMBER ,
            CMTS_SNR_DN NUMBER ,
            CMTS_SNR_DN_1D NUMBER ,
            CMTS_SNR_DN_2D NUMBER ,
            CMTS_SNR_DN_3D NUMBER ,
            CMTS_SNR_DN_4D NUMBER ,
            CMTS_SNR_DN_5D NUMBER ,
            CMTS_CCER_DN_6H NUMBER ,
            CMTS_CCER_DN_12H NUMBER ,
            CMTS_CCER_DN_18H NUMBER ,
            CMTS_CCER_DN NUMBER ,
            CMTS_CCER_DN_1D NUMBER ,
            CMTS_CCER_DN_2D NUMBER ,
            CMTS_CCER_DN_3D NUMBER ,
            CMTS_CCER_DN_4D NUMBER ,
            CMTS_CCER_DN_5D NUMBER ,
            CMTS_CER_DN_6H NUMBER ,
            CMTS_CER_DN_12H NUMBER ,
            CMTS_CER_DN_18H NUMBER ,
            CMTS_CER_DN NUMBER ,
            CMTS_CER_DN_1D NUMBER ,
            CMTS_CER_DN_2D NUMBER ,
            CMTS_CER_DN_3D NUMBER ,
            CMTS_CER_DN_4D NUMBER ,
            CMTS_CER_DN_5D NUMBER ,
            CMTS_UTILIZATION_DN_6H NUMBER ,
            CMTS_UTILIZATION_DN_12H NUMBER ,
            CMTS_UTILIZATION_DN_18H NUMBER ,
            CMTS_UTILIZATION_DN NUMBER ,
            CMTS_UTILIZATION_DN_1D NUMBER ,
            CMTS_UTILIZATION_DN_2D NUMBER ,
            CMTS_UTILIZATION_DN_3D NUMBER ,
            CMTS_UTILIZATION_DN_4D NUMBER ,
            CMTS_UTILIZATION_DN_5D NUMBER ,
            SEQ_ID NUMBER NOT NULL AUTO_INCREMENT
        )';
    END INIT_VECTOR;

    /*
    Creates SAMPLED_VECTORS
    */
    PROCEDURE INIT_SAMPLING AS
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE humoreau.SAMPLED_VECTORS (
            DAY_0 DATE ,
            MAC VARCHAR2(320) ,
            CLY_ACCOUNT_NUMBER VARCHAR2(100 CHAR) ,
            SAA_ACCOUNT_NUMBER VARCHAR2(256 CHAR) ,
            CMTS VARCHAR2(50 CHAR) ,
            SERVICE_GROUP VARCHAR2(50 CHAR) ,
            HARDWARE_MODEL VARCHAR2(80 CHAR) ,
            N_CPE_BUILDING NUMBER ,
            OFFLINE_PCT_6H NUMBER ,
            OFFLINE_PCT_12H NUMBER ,
            OFFLINE_PCT_18H NUMBER ,
            OFFLINE_PCT_24H NUMBER ,
            OFFLINE_PCT NUMBER ,
            OFFLINE_PCT_1D NUMBER ,
            OFFLINE_PCT_2D NUMBER ,
            OFFLINE_PCT_3D NUMBER ,
            OFFLINE_PCT_4D NUMBER ,
            OFFLINE_PCT_5D NUMBER ,
            CER_DN_6H NUMBER ,
            CER_DN_12H NUMBER ,
            CER_DN_18H NUMBER ,
            CER_DN NUMBER ,
            CER_DN_1D NUMBER ,
            CER_DN_2D NUMBER ,
            CER_DN_3D NUMBER ,
            CER_DN_4D NUMBER ,
            CER_DN_5D NUMBER ,
            MISS_CER_DN_6H NUMBER ,
            MISS_CER_DN_12H NUMBER ,
            MISS_CER_DN_18H NUMBER ,
            MISS_CER_DN_24H NUMBER ,
            MISS_CER_DN NUMBER ,
            MISS_CER_DN_1D NUMBER ,
            MISS_CER_DN_2D NUMBER ,
            MISS_CER_DN_3D NUMBER ,
            MISS_CER_DN_4D NUMBER ,
            MISS_CER_DN_5D NUMBER ,
            CER_UP_6H NUMBER ,
            CER_UP_12H NUMBER ,
            CER_UP_18H NUMBER ,
            CER_UP NUMBER ,
            CER_UP_1D NUMBER ,
            CER_UP_2D NUMBER ,
            CER_UP_3D NUMBER ,
            CER_UP_4D NUMBER ,
            CER_UP_5D NUMBER ,
            MISS_CER_UP_6H NUMBER ,
            MISS_CER_UP_12H NUMBER ,
            MISS_CER_UP_18H NUMBER ,
            MISS_CER_UP_24H NUMBER ,
            MISS_CER_UP NUMBER ,
            MISS_CER_UP_1D NUMBER ,
            MISS_CER_UP_2D NUMBER ,
            MISS_CER_UP_3D NUMBER ,
            MISS_CER_UP_4D NUMBER ,
            MISS_CER_UP_5D NUMBER ,
            PCT_TRAFFIC_DMH_UP_6H NUMBER ,
            PCT_TRAFFIC_DMH_UP_12H NUMBER ,
            PCT_TRAFFIC_DMH_UP_18H NUMBER ,
            PCT_TRAFFIC_DMH_UP NUMBER ,
            PCT_TRAFFIC_DMH_UP_1D NUMBER ,
            PCT_TRAFFIC_DMH_UP_2D NUMBER ,
            PCT_TRAFFIC_DMH_UP_3D NUMBER ,
            PCT_TRAFFIC_DMH_UP_4D NUMBER ,
            PCT_TRAFFIC_DMH_UP_5D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_6H NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_12H NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_18H NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_24H NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_1D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_2D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_3D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_4D NUMBER ,
            MISS_PCT_TRAFFIC_DMH_UP_5D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_6H NUMBER ,
            PCT_TRAFFIC_SDMH_UP_12H NUMBER ,
            PCT_TRAFFIC_SDMH_UP_18H NUMBER ,
            PCT_TRAFFIC_SDMH_UP NUMBER ,
            PCT_TRAFFIC_SDMH_UP_1D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_2D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_3D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_4D NUMBER ,
            PCT_TRAFFIC_SDMH_UP_5D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_6H NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_12H NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_18H NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_24H NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_1D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_2D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_3D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_4D NUMBER ,
            MISS_PCT_TRAFFIC_SDMH_UP_5D NUMBER ,
            RX_DN_6H NUMBER ,
            RX_DN_12H NUMBER ,
            RX_DN_18H NUMBER ,
            RX_DN NUMBER ,
            RX_DN_1D NUMBER ,
            RX_DN_2D NUMBER ,
            RX_DN_3D NUMBER ,
            RX_DN_4D NUMBER ,
            RX_DN_5D NUMBER ,
            MISS_RX_DN_6H NUMBER ,
            MISS_RX_DN_12H NUMBER ,
            MISS_RX_DN_18H NUMBER ,
            MISS_RX_DN_24H NUMBER ,
            MISS_RX_DN NUMBER ,
            MISS_RX_DN_1D NUMBER ,
            MISS_RX_DN_2D NUMBER ,
            MISS_RX_DN_3D NUMBER ,
            MISS_RX_DN_4D NUMBER ,
            MISS_RX_DN_5D NUMBER ,
            RX_UP_6H NUMBER ,
            RX_UP_12H NUMBER ,
            RX_UP_18H NUMBER ,
            RX_UP NUMBER ,
            RX_UP_1D NUMBER ,
            RX_UP_2D NUMBER ,
            RX_UP_3D NUMBER ,
            RX_UP_4D NUMBER ,
            RX_UP_5D NUMBER ,
            MISS_RX_UP_6H NUMBER ,
            MISS_RX_UP_12H NUMBER ,
            MISS_RX_UP_18H NUMBER ,
            MISS_RX_UP_24H NUMBER ,
            MISS_RX_UP NUMBER ,
            MISS_RX_UP_1D NUMBER ,
            MISS_RX_UP_2D NUMBER ,
            MISS_RX_UP_3D NUMBER ,
            MISS_RX_UP_4D NUMBER ,
            MISS_RX_UP_5D NUMBER ,
            SNR_DN_6H NUMBER ,
            SNR_DN_12H NUMBER ,
            SNR_DN_18H NUMBER ,
            SNR_DN NUMBER ,
            SNR_DN_1D NUMBER ,
            SNR_DN_2D NUMBER ,
            SNR_DN_3D NUMBER ,
            SNR_DN_4D NUMBER ,
            SNR_DN_5D NUMBER ,
            MISS_SNR_DN_6H NUMBER ,
            MISS_SNR_DN_12H NUMBER ,
            MISS_SNR_DN_18H NUMBER ,
            MISS_SNR_DN_24H NUMBER ,
            MISS_SNR_DN NUMBER ,
            MISS_SNR_DN_1D NUMBER ,
            MISS_SNR_DN_2D NUMBER ,
            MISS_SNR_DN_3D NUMBER ,
            MISS_SNR_DN_4D NUMBER ,
            MISS_SNR_DN_5D NUMBER ,
            SNR_UP_6H NUMBER ,
            SNR_UP_12H NUMBER ,
            SNR_UP_18H NUMBER ,
            SNR_UP NUMBER ,
            SNR_UP_1D NUMBER ,
            SNR_UP_2D NUMBER ,
            SNR_UP_3D NUMBER ,
            SNR_UP_4D NUMBER ,
            SNR_UP_5D NUMBER ,
            MISS_SNR_UP_6H NUMBER ,
            MISS_SNR_UP_12H NUMBER ,
            MISS_SNR_UP_18H NUMBER ,
            MISS_SNR_UP_24H NUMBER ,
            MISS_SNR_UP NUMBER ,
            MISS_SNR_UP_1D NUMBER ,
            MISS_SNR_UP_2D NUMBER ,
            MISS_SNR_UP_3D NUMBER ,
            MISS_SNR_UP_4D NUMBER ,
            MISS_SNR_UP_5D NUMBER ,
            TX_UP_6H NUMBER ,
            TX_UP_12H NUMBER ,
            TX_UP_18H NUMBER ,
            TX_UP NUMBER ,
            TX_UP_1D NUMBER ,
            TX_UP_2D NUMBER ,
            TX_UP_3D NUMBER ,
            TX_UP_4D NUMBER ,
            TX_UP_5D NUMBER ,
            MISS_TX_UP_6H NUMBER ,
            MISS_TX_UP_12H NUMBER ,
            MISS_TX_UP_18H NUMBER ,
            MISS_TX_UP_24H NUMBER ,
            MISS_TX_UP NUMBER ,
            MISS_TX_UP_1D NUMBER ,
            MISS_TX_UP_2D NUMBER ,
            MISS_TX_UP_3D NUMBER ,
            MISS_TX_UP_4D NUMBER ,
            MISS_TX_UP_5D NUMBER ,
            CMTS_RX_UP_6H NUMBER ,
            CMTS_RX_UP_12H NUMBER ,
            CMTS_RX_UP_18H NUMBER ,
            CMTS_RX_UP NUMBER ,
            CMTS_RX_UP_1D NUMBER ,
            CMTS_RX_UP_2D NUMBER ,
            CMTS_RX_UP_3D NUMBER ,
            CMTS_RX_UP_4D NUMBER ,
            CMTS_RX_UP_5D NUMBER ,
            CMTS_TX_UP_6H NUMBER ,
            CMTS_TX_UP_12H NUMBER ,
            CMTS_TX_UP_18H NUMBER ,
            CMTS_TX_UP NUMBER ,
            CMTS_TX_UP_1D NUMBER ,
            CMTS_TX_UP_2D NUMBER ,
            CMTS_TX_UP_3D NUMBER ,
            CMTS_TX_UP_4D NUMBER ,
            CMTS_TX_UP_5D NUMBER ,
            CMTS_CER_UP_6H NUMBER ,
            CMTS_CER_UP_12H NUMBER ,
            CMTS_CER_UP_18H NUMBER ,
            CMTS_CER_UP NUMBER ,
            CMTS_CER_UP_1D NUMBER ,
            CMTS_CER_UP_2D NUMBER ,
            CMTS_CER_UP_3D NUMBER ,
            CMTS_CER_UP_4D NUMBER ,
            CMTS_CER_UP_5D NUMBER ,
            CMTS_UTILIZATION_UP_6H NUMBER ,
            CMTS_UTILIZATION_UP_12H NUMBER ,
            CMTS_UTILIZATION_UP_18H NUMBER ,
            CMTS_UTILIZATION_UP NUMBER ,
            CMTS_UTILIZATION_UP_1D NUMBER ,
            CMTS_UTILIZATION_UP_2D NUMBER ,
            CMTS_UTILIZATION_UP_3D NUMBER ,
            CMTS_UTILIZATION_UP_4D NUMBER ,
            CMTS_UTILIZATION_UP_5D NUMBER ,
            CMTS_MS_UTILIZATION_UP_6H NUMBER ,
            CMTS_MS_UTILIZATION_UP_12H NUMBER ,
            CMTS_MS_UTILIZATION_UP_18H NUMBER ,
            CMTS_MS_UTILIZATION_UP NUMBER ,
            CMTS_MS_UTILIZATION_UP_1D NUMBER ,
            CMTS_MS_UTILIZATION_UP_2D NUMBER ,
            CMTS_MS_UTILIZATION_UP_3D NUMBER ,
            CMTS_MS_UTILIZATION_UP_4D NUMBER ,
            CMTS_MS_UTILIZATION_UP_5D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_6H NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_12H NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_18H NUMBER ,
            CMTS_F_MS_UTILIZATION_UP NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_1D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_2D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_3D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_4D NUMBER ,
            CMTS_F_MS_UTILIZATION_UP_5D NUMBER ,
            CMTS_RX_DN_6H NUMBER ,
            CMTS_RX_DN_12H NUMBER ,
            CMTS_RX_DN_18H NUMBER ,
            CMTS_RX_DN NUMBER ,
            CMTS_RX_DN_1D NUMBER ,
            CMTS_RX_DN_2D NUMBER ,
            CMTS_RX_DN_3D NUMBER ,
            CMTS_RX_DN_4D NUMBER ,
            CMTS_RX_DN_5D NUMBER ,
            CMTS_SNR_DN_6H NUMBER ,
            CMTS_SNR_DN_12H NUMBER ,
            CMTS_SNR_DN_18H NUMBER ,
            CMTS_SNR_DN NUMBER ,
            CMTS_SNR_DN_1D NUMBER ,
            CMTS_SNR_DN_2D NUMBER ,
            CMTS_SNR_DN_3D NUMBER ,
            CMTS_SNR_DN_4D NUMBER ,
            CMTS_SNR_DN_5D NUMBER ,
            CMTS_CCER_DN_6H NUMBER ,
            CMTS_CCER_DN_12H NUMBER ,
            CMTS_CCER_DN_18H NUMBER ,
            CMTS_CCER_DN NUMBER ,
            CMTS_CCER_DN_1D NUMBER ,
            CMTS_CCER_DN_2D NUMBER ,
            CMTS_CCER_DN_3D NUMBER ,
            CMTS_CCER_DN_4D NUMBER ,
            CMTS_CCER_DN_5D NUMBER ,
            CMTS_CER_DN_6H NUMBER ,
            CMTS_CER_DN_12H NUMBER ,
            CMTS_CER_DN_18H NUMBER ,
            CMTS_CER_DN NUMBER ,
            CMTS_CER_DN_1D NUMBER ,
            CMTS_CER_DN_2D NUMBER ,
            CMTS_CER_DN_3D NUMBER ,
            CMTS_CER_DN_4D NUMBER ,
            CMTS_CER_DN_5D NUMBER ,
            CMTS_UTILIZATION_DN_6H NUMBER ,
            CMTS_UTILIZATION_DN_12H NUMBER ,
            CMTS_UTILIZATION_DN_18H NUMBER ,
            CMTS_UTILIZATION_DN NUMBER ,
            CMTS_UTILIZATION_DN_1D NUMBER ,
            CMTS_UTILIZATION_DN_2D NUMBER ,
            CMTS_UTILIZATION_DN_3D NUMBER ,
            CMTS_UTILIZATION_DN_4D NUMBER ,
            CMTS_UTILIZATION_DN_5D NUMBER ,
            SEQ_ID NUMBER NOT NULL,
            MILESTONE_NAME  VARCHAR2(256 CHAR)
        )';
    END INIT_SAMPLING;

    /*
    Creates VIA_MACS
    */
    PROCEDURE INIT_VIA AS 
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE HUMOREAU.VIA_MACS as (select * from HUMOREAU.VIA_MACS@DMT2DMP)';
    END INIT_VIA;

    /*
    Creates LOG_TABLE
    */
    PROCEDURE INIT_LOGTABLE AS 
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE HUMOREAU.LOG_TABLE
            (
            LOG_DATE        TIMESTAMP (6)   DEFAULT systimestamp,
            IS_ERROR        NUMBER,
            LOG_TEXT        VARCHAR2(4000),
            IS_DONE         NUMBER
            )';
    END INIT_LOGTABLE;

END CPE_FAIL_DETECTION_POC_INIT;
/
